# models.py — Generated by VIA
# Real SQLAlchemy ORM models — persists to PostgreSQL on Render, SQLite in dev

from sqlalchemy import Column, Integer, String, Text, DateTime, Boolean, Float
from sqlalchemy.orm import relationship
from datetime import datetime
from database import Base



class Item(Base):
    __tablename__ = "items"

    id          = Column(Integer, primary_key=True, index=True)
    title       = Column(String(255), nullable=False, index=True)
    description = Column(Text, nullable=True)
    status      = Column(String(50), default="active", index=True)
    category    = Column(String(100), nullable=True)
    created_at  = Column(DateTime, default=datetime.utcnow)
    updated_at  = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)