services:
  - type: web
    name: create-a-application-for-the-movies
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: VIA
          property: connectionString
      - key: APP_ENV
        value: production
      - key: JWT_SECRET_KEY
        generateValue: true
