# services.py — Generated by VIA
# Business logic helpers (DB ops live directly in routers for simplicity)

from datetime import datetime


def now_iso() -> str:
    return datetime.utcnow().isoformat()


def paginate(query_result: list, skip: int = 0, limit: int = 100) -> list:
    return query_result[skip: skip + limit]