# routers/items.py — Generated by VIA
# Real database CRUD — persists data to PostgreSQL/SQLite via SQLAlchemy

from fastapi import APIRouter, HTTPException, Depends
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, func
from typing import Optional
from datetime import datetime

from database import get_db
from models import Item

router = APIRouter()


@router.get("/items")
async def list_items(
    skip: int = 0,
    limit: int = 100,
    status: Optional[str] = None,
    db: AsyncSession = Depends(get_db),
):
    query = select(Item)
    if status:
        query = query.where(Item.status == status)
    query = query.offset(skip).limit(limit)
    result = await db.execute(query)
    items = result.scalars().all()
    return {"items": [_to_dict(i) for i in items], "total": len(items)}


@router.post("/items", status_code=201)
async def create_item(payload: dict, db: AsyncSession = Depends(get_db)):
    # Map generic "title/description/status" keys to whatever columns exist
    item = Item()
    for key, value in payload.items():
        if hasattr(item, key):
            setattr(item, key, value)
    if not getattr(item, "title", None) and "name" in payload:
        item.title = payload["name"]
    item.created_at = datetime.utcnow()
    item.updated_at = datetime.utcnow()
    db.add(item)
    await db.flush()
    await db.refresh(item)
    return _to_dict(item)


@router.get("/items/{item_id}")
async def get_item(item_id: int, db: AsyncSession = Depends(get_db)):
    result = await db.execute(select(Item).where(Item.id == item_id))
    item = result.scalar_one_or_none()
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")
    return _to_dict(item)


@router.put("/items/{item_id}")
async def update_item(item_id: int, updates: dict, db: AsyncSession = Depends(get_db)):
    result = await db.execute(select(Item).where(Item.id == item_id))
    item = result.scalar_one_or_none()
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")
    for key, value in updates.items():
        if hasattr(item, key) and key not in ("id", "created_at"):
            setattr(item, key, value)
    item.updated_at = datetime.utcnow()
    await db.flush()
    await db.refresh(item)
    return _to_dict(item)


@router.delete("/items/{item_id}")
async def delete_item(item_id: int, db: AsyncSession = Depends(get_db)):
    result = await db.execute(select(Item).where(Item.id == item_id))
    item = result.scalar_one_or_none()
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")
    await db.delete(item)
    return {"deleted": True, "id": item_id}


@router.get("/stats")
async def get_stats(db: AsyncSession = Depends(get_db)):
    total_result = await db.execute(select(func.count()).select_from(Item))
    total = total_result.scalar() or 0
    active_result = await db.execute(
        select(func.count()).select_from(Item).where(Item.status == "active")
    )
    active = active_result.scalar() or 0
    return {"total": total, "active": active}


def _to_dict(obj) -> dict:
    """Convert SQLAlchemy model instance to dict safely."""
    result = {}
    for col in obj.__table__.columns:
        val = getattr(obj, col.name, None)
        if isinstance(val, datetime):
            val = val.isoformat()
        result[col.name] = val
    return result